
const en = {
    "home": "Home Page",
    "signup": "Register",
    "login": "Login",
    "en": "English",
    "ar": "العربية",
    "name": "Name",
    "app_name": "Movies",
    "email": "Email Address",
    "password": "Password",
    "confirm_password": "Confirm Password",
    "username": "Username",
    "searchCourses": "Search for Courses i.e buissness",
    "successStories": "Success Stories From Our Students WorldWide!",
    "accessResources": "Get Access to Unlimited Educational Resources. Everywhere, Everytime!",
    "premiumAccess": "Premium access to more than 10,000 resources ranging from courses, events, etc.",
    "getAccess": "Get Access",
    "platformDescription": "Learnix is an online education platform that delivers video courses, programs and resources for Individuals, Advertising & Media Specialists, Online Marketing Professionals, Freelancers and anyone looking to pursue a career in Digital Marketing, Accounting, Web Development, Programming, Multimedia and CAD Design.",
    "discover": "Discover",
    "courses": "Courses",
    "exploreMoreCourses": "Explore More Courses",
    "unlimitedAccess": "Unlimited Access",
    "oneSubscription": "One Subscription, Unlimited Access",
    "expertTeachers": "Expert Teachers",
    "expertTeachersDesc": "Learn from industry experts who are passionate about teaching",
    "learnAnywhere": "Learn Anywhere",
    "learnAnywhereDesc": "Switch between your computer, tablet, or mobile device",
    "learnSkill": "Learn A Skill.",
    "buildPortfolio": "Build Your Portfolio.",
    "getHired": "Get Hired!",
    "description": `Learnix is an online education platform that delivers video 
                    courses, programs and resources for Individual, Advertising & Media Specialist,
                    Online Marketing Professionals, Freelancers and anyone looking to pursue a career
                    in digital marketing, Accounting, Web development, Programming, Multimedia and CAD design.`,
    "browseTutorials": "Browse Thousands of Our Video Tutorials Curated Only for You.",
    "accessPremium": "Access all tutorials and resources when you become a premium member of",
    "allPrices": "All Prices",
    "learnix": "Learnix",
    "no_account": "Don't have an account?",
    "welcome_back": "Welcome Back!",
    "login_continue": "Log in to continue your learning journey.",
    "email_required": "Email is required",
    "email_format": 'Email should be like "example@xxxx.com"',
    "password_required": "Password is required",
    "password_length": "Password must be more than 8 characters",
    "user_not_found": "User data not found in Firestore",
    "invalid_credentials": "Invalid email or password",
    "show": "Show",
    "hide": "Hide",

    "create_account": "Create Account",
    "have_account": "Already have an account?",
    "welcome_register": "Welcome to Learnix!",
    "register_continue": "Create your account to start your learning journey.",
    "signup_button": "Sign Up",
    "name_required": "Name is required",
    "username_required": "Username is required",
    "confirm_password_required": "Confirm password is required",
    "passwords_not_match": "Passwords do not match",

    "terms1": "By creating an account, you agree to our",
    "terms": "Terms & Conditions",
    "and": "and",
    "privacy": "Privacy Policy",
    "password_rules": "Password must contain at least 1 uppercase, 1 lowercase, 1 number, 1 special character (@#$%^&*!), and be at least 8 characters long",
    "password_mismatch": "Passwords do not match",
    "home_nav": "Home",
    "courses_nav": "Courses",
    "log_out": "Logout",
    "favorite": "Favorite",
    "wishlist": "Wishlist",
    "admin_dashboard": "Admin Dashboard",
    "dashboard_user": "Dashboard",

}

export default en